-- Per-send audit log for the Monday time-log reminder cron.
--
-- One row is written for every outcome recorded by
-- /api/cron/time-log-reminder — including dry-runs and failed sends — so we
-- can later answer questions like "who was reminded last Monday?" and
-- "did Resend fail for anyone?" without needing to replay logs.
--
-- Writes always happen with the service-role key from inside the cron route,
-- so this table is completely off-limits to end users: no RLS policy is
-- needed, we just revoke all grants from anon/authenticated.

create table if not exists public.time_log_reminder_sends (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  email text not null,
  display_name text,
  role text,
  week_start date not null,
  week_end date not null,
  status text not null check (status in ('sent', 'failed', 'skipped_dry_run')),
  message_id text,
  error text,
  mode text not null check (mode in ('cron', 'admin')),
  forced boolean not null default false,
  dry_run boolean not null default false,
  sent_at timestamptz not null default now()
);

create index if not exists idx_time_log_reminder_sends_sent_at
  on public.time_log_reminder_sends (sent_at desc);

create index if not exists idx_time_log_reminder_sends_user_sent_at
  on public.time_log_reminder_sends (user_id, sent_at desc);

create index if not exists idx_time_log_reminder_sends_week
  on public.time_log_reminder_sends (week_start, week_end);

alter table public.time_log_reminder_sends enable row level security;
alter table public.time_log_reminder_sends force row level security;

revoke all on table public.time_log_reminder_sends from anon;
revoke all on table public.time_log_reminder_sends from authenticated;
