-- Durability layer for Time Tracker.
-- Run this once after time-tracker-schema.sql
-- Adds:
-- 1) Immutable audit log for all row mutations
-- 2) Per-user full snapshots that API can trigger before writes

create table if not exists public.time_tracker_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  table_name text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  row_id bigint,
  old_row jsonb,
  new_row jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists idx_time_tracker_audit_user_time
  on public.time_tracker_audit_log (user_id, changed_at desc);

create index if not exists idx_time_tracker_audit_table_time
  on public.time_tracker_audit_log (table_name, changed_at desc);

alter table public.time_tracker_audit_log enable row level security;

drop policy if exists "time_tracker_audit_select_own" on public.time_tracker_audit_log;
create policy "time_tracker_audit_select_own"
  on public.time_tracker_audit_log for select
  using (auth.uid() = user_id);

drop policy if exists "time_tracker_audit_block_insert" on public.time_tracker_audit_log;
create policy "time_tracker_audit_block_insert"
  on public.time_tracker_audit_log for insert
  with check (false);

drop policy if exists "time_tracker_audit_block_update" on public.time_tracker_audit_log;
create policy "time_tracker_audit_block_update"
  on public.time_tracker_audit_log for update
  using (false)
  with check (false);

drop policy if exists "time_tracker_audit_block_delete" on public.time_tracker_audit_log;
create policy "time_tracker_audit_block_delete"
  on public.time_tracker_audit_log for delete
  using (false);

create or replace function public.tt_resolve_audit_user_id(
  p_table_name text,
  p_new_row jsonb,
  p_old_row jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate uuid;
  day_log_id bigint;
begin
  candidate := coalesce(
    nullif(coalesce(p_new_row->>'user_id', p_old_row->>'user_id'), '')::uuid,
    null
  );
  if candidate is not null then
    return candidate;
  end if;

  if p_table_name = 'time_day_breaks' then
    day_log_id := coalesce(
      nullif(coalesce(p_new_row->>'day_log_id', p_old_row->>'day_log_id'), '')::bigint,
      null
    );
    if day_log_id is not null then
      select user_id into candidate
      from public.time_day_logs
      where id = day_log_id;
      return candidate;
    end if;
  end if;

  return null;
end;
$$;

create or replace function public.tt_audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table text := TG_TABLE_NAME;
  v_op text := TG_OP;
  v_row_id bigint;
  v_user_id uuid;
  v_old jsonb := null;
  v_new jsonb := null;
begin
  if TG_OP = 'INSERT' then
    v_new := to_jsonb(NEW);
    v_row_id := NEW.id;
  elsif TG_OP = 'UPDATE' then
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_row_id := NEW.id;
  elsif TG_OP = 'DELETE' then
    v_old := to_jsonb(OLD);
    v_row_id := OLD.id;
  end if;

  v_user_id := public.tt_resolve_audit_user_id(v_table, v_new, v_old);

  insert into public.time_tracker_audit_log (
    user_id,
    table_name,
    operation,
    row_id,
    old_row,
    new_row
  )
  values (
    v_user_id,
    v_table,
    v_op,
    v_row_id,
    v_old,
    v_new
  );

  if TG_OP = 'DELETE' then
    return OLD;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_tt_audit_time_day_logs on public.time_day_logs;
create trigger trg_tt_audit_time_day_logs
after insert or update or delete on public.time_day_logs
for each row execute function public.tt_audit_row_change();

drop trigger if exists trg_tt_audit_time_day_breaks on public.time_day_breaks;
create trigger trg_tt_audit_time_day_breaks
after insert or update or delete on public.time_day_breaks
for each row execute function public.tt_audit_row_change();

drop trigger if exists trg_tt_audit_time_comp_adjustments on public.time_comp_adjustments;
create trigger trg_tt_audit_time_comp_adjustments
after insert or update or delete on public.time_comp_adjustments
for each row execute function public.tt_audit_row_change();

create table if not exists public.time_tracker_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  reason text not null default 'manual',
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_time_tracker_snapshots_user_time
  on public.time_tracker_snapshots (user_id, created_at desc);

alter table public.time_tracker_snapshots enable row level security;
alter table public.time_tracker_snapshots force row level security;

revoke all on table public.time_tracker_audit_log from anon;
revoke all on table public.time_tracker_snapshots from anon;
revoke all on table public.time_tracker_audit_log from authenticated;
revoke all on table public.time_tracker_snapshots from authenticated;
grant select on table public.time_tracker_audit_log to authenticated;
grant select, insert on table public.time_tracker_snapshots to authenticated;

drop policy if exists "time_tracker_snapshots_select_own" on public.time_tracker_snapshots;
create policy "time_tracker_snapshots_select_own"
  on public.time_tracker_snapshots for select
  using (auth.uid() = user_id);

drop policy if exists "time_tracker_snapshots_insert_own" on public.time_tracker_snapshots;
create policy "time_tracker_snapshots_insert_own"
  on public.time_tracker_snapshots for insert
  with check (auth.uid() = user_id);

drop policy if exists "time_tracker_snapshots_update_block" on public.time_tracker_snapshots;
create policy "time_tracker_snapshots_update_block"
  on public.time_tracker_snapshots for update
  using (false)
  with check (false);

drop policy if exists "time_tracker_snapshots_delete_block" on public.time_tracker_snapshots;
create policy "time_tracker_snapshots_delete_block"
  on public.time_tracker_snapshots for delete
  using (false);

create or replace function public.create_time_tracker_snapshot(
  p_user uuid,
  p_reason text default 'manual'
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_snapshot_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;
  if auth.uid() <> p_user then
    raise exception 'Not allowed for this user';
  end if;

  insert into public.time_tracker_snapshots (
    user_id,
    reason,
    snapshot
  )
  values (
    p_user,
    coalesce(nullif(p_reason, ''), 'manual'),
    jsonb_build_object(
      'time_day_logs', (
        select coalesce(
          jsonb_agg(to_jsonb(t) order by t.work_date, t.id),
          '[]'::jsonb
        )
        from public.time_day_logs t
        where t.user_id = p_user
      ),
      'time_day_breaks', (
        select coalesce(
          jsonb_agg(to_jsonb(b) order by b.day_log_id, b.position, b.id),
          '[]'::jsonb
        )
        from public.time_day_breaks b
        join public.time_day_logs t on t.id = b.day_log_id
        where t.user_id = p_user
      ),
      'time_comp_adjustments', (
        select coalesce(
          jsonb_agg(to_jsonb(c) order by c.work_date, c.id),
          '[]'::jsonb
        )
        from public.time_comp_adjustments c
        where c.user_id = p_user
      )
    )
  )
  returning id into v_snapshot_id;

  return v_snapshot_id;
end;
$$;

revoke all on function public.create_time_tracker_snapshot(uuid, text) from public;
grant execute on function public.create_time_tracker_snapshot(uuid, text) to authenticated;
