-- Time Tracker storage schema for per-user data.
-- Run this once in Supabase SQL Editor before importing historical data.

create table if not exists public.time_day_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  work_date date not null,
  start_time text,
  stop_time text,
  net_mins integer not null default 0 check (net_mins >= 0),
  holiday boolean not null default false,
  source text not null default 'hourlogger_import',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create table if not exists public.time_day_breaks (
  id bigint generated by default as identity primary key,
  day_log_id bigint not null references public.time_day_logs (id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  name text not null default '',
  mins integer not null default 0 check (mins >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.time_comp_adjustments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  work_date date not null,
  mins integer not null default 0 check (mins >= 0),
  note text not null default '',
  source text not null default 'hourlogger_import',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create index if not exists idx_time_day_logs_user_date on public.time_day_logs (user_id, work_date);
create index if not exists idx_time_day_breaks_day on public.time_day_breaks (day_log_id, position);
create index if not exists idx_time_comp_adjustments_user_date on public.time_comp_adjustments (user_id, work_date);

alter table public.time_day_logs enable row level security;
alter table public.time_day_breaks enable row level security;
alter table public.time_comp_adjustments enable row level security;

drop policy if exists "time_day_logs_select_own" on public.time_day_logs;
create policy "time_day_logs_select_own"
  on public.time_day_logs for select
  using (auth.uid() = user_id);

drop policy if exists "time_day_logs_insert_own" on public.time_day_logs;
create policy "time_day_logs_insert_own"
  on public.time_day_logs for insert
  with check (auth.uid() = user_id);

drop policy if exists "time_day_logs_update_own" on public.time_day_logs;
create policy "time_day_logs_update_own"
  on public.time_day_logs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "time_day_logs_delete_own" on public.time_day_logs;
create policy "time_day_logs_delete_own"
  on public.time_day_logs for delete
  using (auth.uid() = user_id);

drop policy if exists "time_day_breaks_select_own" on public.time_day_breaks;
create policy "time_day_breaks_select_own"
  on public.time_day_breaks for select
  using (
    exists (
      select 1
      from public.time_day_logs logs
      where logs.id = time_day_breaks.day_log_id
        and logs.user_id = auth.uid()
    )
  );

drop policy if exists "time_day_breaks_insert_own" on public.time_day_breaks;
create policy "time_day_breaks_insert_own"
  on public.time_day_breaks for insert
  with check (
    exists (
      select 1
      from public.time_day_logs logs
      where logs.id = time_day_breaks.day_log_id
        and logs.user_id = auth.uid()
    )
  );

drop policy if exists "time_day_breaks_update_own" on public.time_day_breaks;
create policy "time_day_breaks_update_own"
  on public.time_day_breaks for update
  using (
    exists (
      select 1
      from public.time_day_logs logs
      where logs.id = time_day_breaks.day_log_id
        and logs.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.time_day_logs logs
      where logs.id = time_day_breaks.day_log_id
        and logs.user_id = auth.uid()
    )
  );

drop policy if exists "time_day_breaks_delete_own" on public.time_day_breaks;
create policy "time_day_breaks_delete_own"
  on public.time_day_breaks for delete
  using (
    exists (
      select 1
      from public.time_day_logs logs
      where logs.id = time_day_breaks.day_log_id
        and logs.user_id = auth.uid()
    )
  );

drop policy if exists "time_comp_adjustments_select_own" on public.time_comp_adjustments;
create policy "time_comp_adjustments_select_own"
  on public.time_comp_adjustments for select
  using (auth.uid() = user_id);

drop policy if exists "time_comp_adjustments_insert_own" on public.time_comp_adjustments;
create policy "time_comp_adjustments_insert_own"
  on public.time_comp_adjustments for insert
  with check (auth.uid() = user_id);

drop policy if exists "time_comp_adjustments_update_own" on public.time_comp_adjustments;
create policy "time_comp_adjustments_update_own"
  on public.time_comp_adjustments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "time_comp_adjustments_delete_own" on public.time_comp_adjustments;
create policy "time_comp_adjustments_delete_own"
  on public.time_comp_adjustments for delete
  using (auth.uid() = user_id);
